name: Build and deploy production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/docker-release.yml
    with:
      environment: production
      release_tag: production-${{ github.sha }}
    secrets: inherit
