name: Build and deploy staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/docker-release.yml
    with:
      environment: staging
      release_tag: staging-${{ github.sha }}
    secrets: inherit
